benchmark/urls.py
from django.urls import path

from . import views

app_name = 'benchmark'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('score/', views.score, name='score'),
    path('run/', views.run, name='run'),
    path('evaluate/', views.evaluate, name='evaluate'),
    path('compare/', views.compare, name='compare'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('list/', views.ListView.as_view(), name='list'),

    # ex: /benchmark/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # ex: /benchmark/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    # ex: /benchmark/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

bml/benchmark/urls.py
from django.urls import path

from . import views

app_name = 'benchmark'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),

    path('score/', views.score, name='score'),
    path('docscore/', views.docscore, name='docscore'),
    path('run/', views.run, name='run'),
    path('doctrain/', views.doctrain, name='doctrain'),
    path('evaluate/', views.evaluate, name='evaluate'),
    path('compare/', views.compare, name='compare'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('test/', views.test, name='test'),
    #path('list/', views.ListView.as_view(), name='list'),

    ## ex: /benchmark/5/
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    ## ex: /benchmark/5/results/
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    ## ex: /benchmark/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('benchmark/', include('benchmark.urls')),
    path('admin/', admin.site.urls),
]

benchmark/models.py
import datetime
from django.db import models
from django.utils import timezone

# users
class Web_User(models.Model):
    def __str__(self):
        return self.id
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

# files loaded
class File_raw(models.Model):
    def __str__(self):
        return self.file_name
    def get_file_desc(self):
        return self.file_desc
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    web_user = models.ForeignKey(Web_User, on_delete=models.CASCADE)
    file_name = models.CharField(max_length=200)
    file_desc = models.CharField(max_length=200)
    number_features = models.CharField(max_length=200)
    methods = models.CharField(max_length=200)
    percent_train = models.CharField(max_length=200)
    dist_class = models.CharField(max_length=200)
    target_class = models.CharField(max_length=200)
    file_type = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

# Create your models here.
class Model_Run(models.Model):
    def __str__(self):
        return self.id
    def get_model_ran(self):
        return self.model_ran
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    file_raw = models.ForeignKey(File_raw, on_delete=models.CASCADE)
    model_ran = models.CharField(max_length=200)
    notes = models.CharField(max_length=200)
    epochs = models.IntegerField(default=50)
    weighted_accuracy = models.FloatField(default=0)
    pub_date = models.DateTimeField('date published')

# Create your models here.
class Model_Run_Steps(models.Model):
    def __str__(self):
        return self.id
    model_run = models.ForeignKey(Model_Run, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)
    step = models.CharField(max_length=200)
    value = models.CharField(max_length=200)

# Create your models here.
class Model_Run_Features(models.Model):
    def __str__(self):
        return self.id
    model_run = models.ForeignKey(Model_Run, on_delete=models.CASCADE)
    method = models.CharField(max_length=200)
    num_features = models.CharField(max_length=200)
    accuracy_score = models.FloatField(default=0)
    pub_date = models.DateTimeField('date published')

# Create your models here.
class Classification_Report(models.Model):
    def __str__(self):
        return self.id
    model_run_features = models.ForeignKey(Model_Run_Features, on_delete=models.CASCADE)
    class_name = models.CharField(max_length=200)
    precision = models.FloatField(default=0)
    recall = models.FloatField(default=0)
    f1_score = models.FloatField(default=0)
    support = models.FloatField(default=0)
    pub_date = models.DateTimeField('date published')

# Create your models here.
class Confusion_Matrix(models.Model):
    def __str__(self):
        return self.id
    model_run_features = models.ForeignKey(Model_Run_Features, on_delete=models.CASCADE)
    x = models.IntegerField()
    y = models.IntegerField()
    quantity = models.IntegerField()
    pub_date = models.DateTimeField('date published')

# Create your models here.
class Class_Number(models.Model):
    def __str__(self):
        return self.id
    file_raw = models.ForeignKey(File_raw, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    to_number = models.IntegerField()
    pub_date = models.DateTimeField('date published')

# Create your models here.
class Question(models.Model):
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

# not sure if this should go here
datetime.timedelta(days=1)

class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

benchmark/views.py
# views.py is the view of django
# is quite big <500 lines, i should refactor

import os, glob

# django libraries
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.files.storage import FileSystemStorage
from django.template.defaulttags import register
from django.contrib.auth import logout

# database tables
from .models import Choice, Question, File_raw, Model_Run, Model_Run_Steps, Model_Run_Features
from .models import Classification_Report, Confusion_Matrix, Web_User

# business layer
from .ScoreFeatures import ScoreFeatures
from .SplitTrainTest import SplitTrainTest
from .pca_filter_features import readGenesScoringFile, readHeadersFile, readInputFile
from .ModelConv1D import ModelConv1D
from .ModelFullyConnected import ModelFullyConnected
from .ModelBNN import ModelBNN
from .GaussianNaiveBayes import GaussianNaiveBayes
from .DecisionTree import DecisionTree
from .RandomForest import RandomForest
from .SupportVectorMachine import SupportVectorMachine
from .Pca3D import buildPcaImage

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'benchmark/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class ListView(generic.ListView):
    template_name = 'benchmark/list.html'
    context_object_name = 'latest_question_list'
    active='Compare'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'benchmark/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'benchmark/results.html'

# build pca image file
def buildPca(fileRawId, filename, targetClass):
    nameOnly = filename[filename.rfind('/')+1:len(filename)]
    buildPcaImage(filename, filename + '.genes', 'benchmark/static/benchmark/images/' + nameOnly + '.pca.png', targetClass)

# upload file to be scored
# https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
def score(request):
    if 'userid' not in request.session or request.session['userid'] == None:
        return render(request, 'benchmark/signin.html', {
            'message':'Please enter username and password',
            'active':"Signin",
        })
    
    if request.method == 'POST' and request.FILES['myfile']:

        # insert row into database table file_raw
        myfile = request.FILES['myfile']
        r = File_raw(web_user_id=request.session['userid'], file_name=myfile.name, file_desc=request.POST['fileDesc'], number_features=request.POST['numberFeatures'], methods=request.POST['methods'], percent_train=request.POST['trainingPercent'], dist_class=request.POST['distClass'], target_class=request.POST['targetClass'], file_type=request.POST['fileType'], pub_date=timezone.now())
        r.save()
        r.file_name = str(r.id) + '_' + r.file_name
        r.save()

        # upload file
        fs = FileSystemStorage()
        filename = fs.save('benchmark/files/'+r.file_name, myfile)
        uploaded_file_url = fs.url(filename)

        # score file with multiple number of features
        featureFiles = ScoreFeatures.scoreTrain( None, filename, r.file_type, r.number_features, r.methods, r.target_class)

        # split data into train and test each features file
        methodsList = r.methods.split(',')
        featuresList = r.number_features.split(',')

        for method in methodsList:
            for numFeat in featuresList:

                genesScoredFile = filename+'.'+method+'.'+numFeat+'.scores'
                featFile = filename + '.' + method + '.' + numFeat

                #if numFeat != 'all':
                # get top features from scored features
                topGenes = readGenesScoringFile(genesScoredFile, numFeat)
                # create genes files in single line in tsv format to be used in pca
                headersGenes = readHeadersFile(filename, topGenes, featFile+'.genes', r.file_type)
                # creates features file with target class and features selected
                readInputFile(filename, r.file_type, featFile, headersGenes, r.target_class)
                #raise Exception('stopping here')

                # split train/test data
                targetCol, retGenes, retClasses = SplitTrainTest.readGenesScoringFile(None, filename, r.file_type, request.POST['targetClass'])
                linesTraining, linesTest = SplitTrainTest.writeOutputFiles(None, int(r.percent_train), targetCol, retGenes, retClasses, featFile+'.train', featFile+'.test')

                # create pca image file
                buildPca(r.id, featFile, r.target_class)

        return render(request, 'benchmark/score.html', {
            'file_raw_list': File_raw.objects.filter(web_user_id=request.session['userid']).order_by('-pub_date'),
            'uploaded_file_url': uploaded_file_url,
            'active':"Load",
        })
    return render(request, 'benchmark/score.html', {
        'file_raw_list': File_raw.objects.filter(web_user_id=request.session['userid']).order_by('-pub_date'),
        'active':"Load",
    })

# run specific model
def specificModel(fileRaw, method, nFeats, modelRan, idModelRunFeatures, parametersList, epochs, targetClass, idFileRaw):

    fileName = 'benchmark/files/'+ fileRaw.file_name + '.' + method + '.' + nFeats
    if modelRan == 'Conv1D':
        classifier = ModelConv1D()
        accuracyScore = classifier.runModel(idModelRunFeatures, fileName+'.train', fileName+'.test', parametersList, epochs, targetClass, True, fileRaw.id)
    else:
        if modelRan == 'FC':
            classifier = ModelFullyConnected()
            accuracyScore = classifier.runModel(idModelRunFeatures, fileName+'.train', fileName+'.test', parametersList, epochs, targetClass, True, fileRaw.id)
        else:
            if modelRan == 'RF':
                classifier = RandomForest()
                accuracyScore = classifier.runModel(idModelRunFeatures, fileName+'.train', fileName+'.test', parametersList, epochs, targetClass, True, fileRaw.id)
            else:
                if modelRan == 'SVM':
                    classifier = SupportVectorMachine()
                    accuracyScore = classifier.runModel(idModelRunFeatures, fileName+'.train', fileName+'.test', parametersList, epochs, targetClass, True, fileRaw.id)
                else:
                    if modelRan == 'GaussianNB':
                        classifier = GaussianNaiveBayes()
                        accuracyScore = classifier.runModel(idModelRunFeatures, fileName+'.train', fileName+'.test', parametersList, epochs, targetClass, True, fileRaw.id)
                    else:
                        if modelRan == 'DT':
                            classifier = DecisionTree()
                            accuracyScore = classifier.runModel(idModelRunFeatures, fileName+'.train', fileName+'.test', parametersList, epochs, targetClass, True, fileRaw.id)
                        else:
                            if modelRan == 'BNN':
                                classifier = ModelBNN()
                                accuracyScore = classifier.runModel(idModelRunFeatures, fileName+'.train', fileName+'.test', parametersList, epochs, targetClass, True, fileRaw.id)
    return accuracyScore

# run ML model
def run(request):
    if 'userid' not in request.session or request.session['userid'] == None:
        return render(request, 'benchmark/signin.html', {
            'message':'Please enter username and password',
            'active':"Signin",
        })
    
    if request.method == 'POST':
        print('runModel', request.POST['idSelected'])
        request.session['idSelected'] = int(request.POST['idSelected'])
        fileRaw = get_object_or_404(File_raw, pk=request.POST['idSelected'])
        print('runModel fileRaw', fileRaw, fileRaw.id, type(fileRaw.id), request.session['idSelected'], type(request.session['idSelected']))

        # save to database
        mr = Model_Run(file_raw_id=int(request.POST['idSelected']), model_ran=request.POST['model_ran'], notes=request.POST['notes'], epochs=int(request.POST['epochs']), pub_date=timezone.now())
        mr.save()

        orderStep = 1
        fcList = ['filters','activation','activation_output','optimizer','loss','learning_rate','model_option','dropout','earlystop']
        for param in fcList:
            if param in request.POST:
                mrs = Model_Run_Steps(model_run_id=mr.id, order=orderStep, step=param, value=request.POST[param])
                mrs.save()
                orderStep += 1

        weightedAccuracy = 0
        countAccuracy = 0
        for method in fileRaw.methods.split(','):
            for nFeats in fileRaw.number_features.split(','):
                # save to database
                mrf = Model_Run_Features(model_run_id=mr.id,
                                         method=method,
                                         num_features=nFeats,
                                         pub_date=timezone.now())
                mrf.save()

                # get parameters for model to run
                parametersList = getParametersList({mr}, True)

                # run model
                accuracyScore = specificModel(fileRaw, method, nFeats, request.POST['model_ran'], int(mrf.id), parametersList, int(request.POST['epochs']), fileRaw.target_class, fileRaw.id)
                mrf.accuracy_score = accuracyScore

benchmark/templates/benchmark/compare.html
{% load static %}

{% include 'benchmark/header.html' %}

{% block content %}
<form method="post" id="evaluateForm" enctype="multipart/form-data">
    {% csrf_token %}

    <body style="margin:8;padding:8;">
    <br> <br>
    <h5 align="left">Select a dataset/file to compare</h2>

    <input type="hidden" id="radioSelection" name="radioSelection">

    {% if file_raw_list %}
        <ul>
        <table style="width:100%;padding:10px">
          <tr>
            <th style="padding:2px"></td>
            <th style="padding:2px">ID</td>
            <th style="padding:2px">FILE NAME</td>
            <th style="padding:2px">FILE DESCRIPTION</td>
            <th style="padding:2px">SCORING</td>
            <th style="padding:2px"># OF FEATURES</td>
            <th style="padding:2px">TRAIN</td>
            <th style="padding:2px">TARGET</td>
            <th style="padding:2px">CREATED DATE</td>
          </tr>
        {% for fileRaw in file_raw_list %}
          <tr>
            <td style="padding:2px">
                <input type="radio" id="idSelected" name="idSelected" value="{{fileRaw.id}}" onclick="document.getElementById('radioSelection').value=1; document.getElementById('evaluateForm').submit();" {% if idSelected == fileRaw.id %} checked {% endif %}>
            </td>
            <td style="padding:2px">{{ fileRaw.id }}</td>
            <td style="padding:2px">{{fileRaw.file_name}}</td>
            <td style="padding:2px">{{fileRaw.file_desc}}</td>
            <td style="padding:2px">{{fileRaw.methods}}</td>
            <td style="padding:2px">{{fileRaw.number_features}}</td>
            <td style="padding:2px">{{fileRaw.percent_train}}%</td>
            <td style="padding:2px">{{fileRaw.target_class}}</td>
            <td style="padding:2px">{{fileRaw.pub_date}}</td>
          </tr>
        {% endfor %}
        </table>
        </ul>
    {% else %}
        <br><br>
        <p>No files has been scored.</p>
    {% endif %}

{% endblock %}

<hr>

{% if model_run_list %}
    <ul>
    <table style="width:100%;padding:10px">
      <tr>
        <th style="padding:2px"></td>
        <th style="padding:2px">ID</td>
        <th style="padding:2px">FILE ID</td>
        <th style="padding:2px">MODEL</td>
        <th style="padding:2px">NOTES</td>
        <th style="padding:2px">EPOCHS</td>
        <th style="padding:2px">ACCURACY</td>
        <th style="padding:2px">PARAMETERS</td>
      </tr>
    {% for modelRun in model_run_list %}
      <tr>
        <td style="padding:2px">
            <input type="radio" id="id_model_run" name="id_model_run" value="{{modelRun.id}}" onclick="document.getElementById('radioSelection').value=2; document.getElementById('evaluateForm').submit();" {% if idModelRun == modelRun.id %} checked {%endif%}>
        </td>
        <td style="padding:2px">{{ modelRun.id }}</td>
        <td style="padding:2px">{{modelRun.file_raw_id}}</td>
        <td style="padding:2px">{{modelRun.model_ran}}</td>
        <td style="padding:2px">{{modelRun.notes}}</td>
        <td style="padding:2px">{{modelRun.epochs}}</td>
        <td style="padding:2px">{{modelRun.weighted_accuracy|floatformat:4}}</td>
        <td style="padding:2px">
        {{ parametersList|getDictValue:modelRun.id }}
        </td>
      </tr>
    {% endfor %}
    </table>
    </ul>
{% else %}
    <br><br>
    <p>No runs has been made for this dataset. Select a file id from above</p>
{% endif %}

<hr>

{% if model_run_features_list %}
    <ul>
    <table style="width:100%;padding:10px">
      <tr>
        <th style="padding:2px"></td>
        <th style="padding:2px">ID</td>
        <th style="padding:2px">MODEL ID</td>
        <th style="padding:2px">SCORED-FEATURES</td>
        <th style="padding:2px">ACCURACY</td>
        <th style="padding:2px">CREATED DATE</td>
      </tr>
    {% for modelRunFeatures in model_run_features_list %}
      <tr>
        <td style="padding:2px">
            <input type="radio" id="id_model_run_features" name="id_model_run_features" value="{{modelRunFeatures.id}}" onclick="document.getElementById('radioSelection').value=3; document.getElementById('evaluateForm').submit();" {% if idModelRunFeatures == modelRunFeatures.id %} checked {% endif %}>
        </td>
        <td style="padding:2px">{{modelRunFeatures.id}}</td>
        <td style="padding:2px">{{modelRunFeatures.model_run_id}}</td>
        <td style="padding:2px">{{modelRunFeatures.method}}-{{modelRunFeatures.num_features}}</td>
        <td style="padding:2px">{{modelRunFeatures.accuracy_score|floatformat:4}}</td>
        <td style="padding:2px">{{modelRunFeatures.pub_date}}</td>
      </tr>
    {% endfor %}
    </table>
    </ul>
{% else %}
    <br><br>
    <p>No models to evaluate. Select a run id from above</p>
{% endif %}

<hr>

<div class="row">
{% if classification_report_list %}
  <div class="col-md-6 mb-3">
    <table style="width:100%;padding:10px">
      <tr>
        <th colspan="5" style="padding:2px">Classification Report</td>
      </tr>
      <tr>
        <td style="padding:2px">CLASS</td>
        <td style="padding:2px">PRECISION</td>
        <td style="padding:2px">RECALL</td>
        <td style="padding:2px">F1-SCORE</td>
        <td style="padding:2px">SUPPORT</td>
      </tr>
    {% for cr in classification_report_list %}
      <tr>
        <td style="padding:2px">{{cr.class_name}}</td>
        <td style="padding:2px">{{cr.precision|floatformat:4}}</td>
        <td style="padding:2px">{{cr.recall|floatformat:4}}</td>
        <td style="padding:2px">{{cr.f1_score|floatformat:4}}</td>
        <td style="padding:2px">{{cr.support|floatformat}}</td>
      </tr>
    {% endfor %}
    </table>
  </div>
  <div class="col-md-6 mb-3">
    {% if confusion_matrix_list %}
      <table style="width:100%;padding:10px">
        <tr>
          <th colspan="{{confusion_matrix_list|length}}" style="padding:2px">Confusion Matrix</td>
        </tr>
        <tr>
          <td colspan="{{confusion_matrix_list|length}}" style="padding:2px">&nbsp</td>
        </tr>
        {% for cm in confusion_matrix_list %}
          {% if cm.y == 0 %}
            {% if cm.x > 0 %}
              </tr>
            {% endif %}
            <tr>
          {% endif %}
          {% if cm.x == cm.y %}
            <td style="padding:2px"><b>{{cm.quantity}}</b></td>
          {% else %}
            <td style="padding:2px">{{cm.quantity}}</td>
          {% endif %}
        {% endfor %}
        </tr>
      </table>
    {% endif %}
  </div>
</div>
{% else %}
    <br><br>
    <p>No details i.e. PCA, accuracy curve, loss curve, classification report, confusion matrix</p>
{% endif %}

<div class="row">
{% if accuracy_curve %}
    <table style="width:100%;padding:10px" widht="100%">
      <tr width="100%">
        <td style="padding:2px" width="50%" align="center">
          <img src={{accuracy_curve}} alt="accuracy curve" width="460" height="280">
        </td>
        <td style="padding:2px" width="50%" align="center">
          <img src={{loss_curve}} alt="loss curve" width="460" height="280">
        </td>
        </td>
      </tr>
      <tr width="100%">
        <td colspan="2" style="padding:2px" width="100%" align="center">
          <img src='/static/benchmark/images/{{idSelected|stringformat:"i"}}_pca.png' alt="loss curve" width="660" height="680">
        </td>
      </tr>
    </table>
{% endif %}
{% if not accuracy_curve and not loss_curve %}
    <br><br>
    <p>No accuracy curve nor loss curve</p>
{% endif %}
</form>

benchmark/templates/benchmark/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'benchmark:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

benchmark/templates/benchmark/header.html
{% load static %}
<header>


<link rel="stylesheet" type="text/css" href="{% static 'benchmark/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'benchmark/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'benchmark/benchmark.js' %}"></script>
<script type="text/javascript" src="{% static 'benchmark/jquery.slim.min.js' %}"></script>
<script type="text/javascript" src="{% static 'benchmark/bootstrap.bundle.min.js' %}"></script>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Benchmark Machine Learning Models webapp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item {% if active == None or active == "Home" %}active{% endif %}">
          <a class="nav-link" href="{% url 'benchmark:index' %}">Home <span class="sr-only">(current)</span> </a>
        </li>
        <li class="nav-item {% if active == "Load" %}active{% endif %}">
          <a class="nav-link" href="{% url 'benchmark:score' %}">Load</a>
        </li>
        <li class="nav-item {% if active == "Run" %}active{% endif %}">
          <a class="nav-link" href="{% url 'benchmark:run' %}">Run</a>
        </li>
        <li class="nav-item {% if active == "Evaluate" %}active{% endif %}">
          <a class="nav-link" href="{% url 'benchmark:evaluate' %}">Evaluate</a>
        </li>
        <li class="nav-item {% if active == "Compare" %}active{% endif %}">
          <a class="nav-link" href="{% url 'benchmark:compare' %}">Compare</a>
        </li>
        <li class="nav-item">
          <a class="nav-link">-</a>
        </li>
        {% if request.session.userid == None %}
          <li class="nav-item {% if active == "Signin" %}active{% endif %}">
            <a class="nav-link" href="{% url 'benchmark:signin' %}">Sign In</a>
          </li>
        {% else %}
          <li class="nav-item {% if active == "Signout" %}active{% endif %}">
            <a class="nav-link" href="{% url 'benchmark:signout' %}">Sign out</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
 
</header>

benchmark/templates/benchmark/list.html
{% load static %}

{% include 'benchmark/header.html' %}

<br> <br> <br>
<h2 align="center">Compare Models Performance</h2>
<p class="lead">.</p>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'benchmark:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No benchmarks are available.</p>
{% endif %}

benchmark/templates/benchmark/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'benchmark:detail' question.id %}">Vote again?</a>